version: 2
jobs:
  docker-build:
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build .
workflows:
  version: 2
  build:
    jobs:
      - docker-build
